// <auto-generated />
using HeyTravel.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HeyTravel.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220222100703_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.13");

            modelBuilder.Entity("HeyTravel.Models.Associazione", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ID_Viaggio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username_Utente")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("eleAssociazione");
                });

            modelBuilder.Entity("HeyTravel.Models.Viaggio", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CittaArrivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MeseArrivo")
                        .HasColumnType("TEXT");

                    b.Property<string>("MesePartenza")
                        .HasColumnType("TEXT");

                    b.Property<string>("StatoArrivo")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.ToTable("eleViaggi");
                });
#pragma warning restore 612, 618
        }
    }
}
